- ghc-events.cabal
`ghc-events` is currently [excluded from Stackage](https://github.com/fpco/stackage/blob/3370a896961687b1c6ab6cef6e7766b9c240bf45/build-constraints.yaml#L764) due to its restrictive upper version bounds on `binary`, as GHC 8.0.1 is shipped with `binary-0.8.3.0`.
> Bump binary upper version bounds

- ghc-events.cabal
This is mainly for my convenience. I don't have `debug_p` version of RTS so profiling build always fails with
```
ld: library not found for -lHSrts_debug_p
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`clang' failed in phase `Linker'. (Exit code: 1)
```
If there a good reason to use `-debug` for the `ghc-events` executable? If not, let's drop it.
> Use the default GHC RTS in the ghc-events executable

- ghc-events.cabal
- src/GHC/RTS/Events.hs
- src/GHC/RTS/EventsIncremental.hs
This PR does two speed optimizations:
* Use bytestring builder rather than String to pretty print events
* Avoid repetitive reconstruction of event decoder
The improvement is rather drastic:
```
% ls -lh ghc-events.eventlog
-rw-r--r--  1 maoe  staff    54M Feb 10 18:30 ghc-events.eventlog
% cat ghc-events.eventlog > /dev/null
% ./ghc-events.master inc ghc-events.eventlog > master.out +RTS -sstderr
207,094,188,704 bytes allocated in the heap
1,387,436,192 bytes copied during GC
92,904 bytes maximum residency (2 sample(s))
44,920 bytes maximum slop
2 MB total memory in use (0 MB lost due to fragmentation)
Tot time (elapsed)  Avg pause  Max pause
Gen  0     397464 colls,     0 par    9.747s   9.987s     0.0000s    0.0012s
Gen  1         2 colls,     0 par    0.001s   0.001s     0.0004s …
```
> Speed optimizations

- ghc-events.cabal
There seem to be no breaking changes in binary-0.9.
https://github.com/kolmodin/binary/blob/master/changelog.md#binary-0900
> Relax upper version bound for binary

- src/GHC/RTS/EventTypes.hs
If I compile with ghc-8.0.2-rc1 I get
```
src/GHC/RTS/EventTypes.hs:527:33: warning: [-Woverflowed-literals]
Literal -1 is out of the Word16 range 0..65535
|
527 |   guard $ fromIntegral cap /= (-1 :: Word16)
| 
```
This is a fix for the issue.
> Fix overflowed literals warning

- src/GHC/RTS/Events.hs
- test/WriteMerge.hs
The write-merge test got broken when I merged #22. This fixes the compilation errors. Note that this doesn't fix #14.
> Make write-merge test buildable

- src/GHC/RTS/Events/Incremental.hs
I noticed a memory leak when opening large eventlog files.   I'm not sure why the original version runs linear in space, but replacing the helper function *f* inside *readEvents* with a version that avoids *break* seems to fix it.  I also fixed a few comment typos while I was in there.
> Fixed memory-leak in incremental readEvents.

- ghc-events.cabal
> Tighten lower bound for base to exclude GHC < 7.8

- cabal.project
- ghc-events.cabal
- src/GHC/RTS/Events/Incremental.hs
Use `Left` explicitly instead of `fail`
to avoid breakage with Monad fail.
Add cabal.project file.
Bump version to 0.9.1
> Fixes for newer cabal/ghc versions.

- ghc-events.cabal
- src/GHC/RTS/Events/Binary.hs
- test/Roundtrip.hs
Previously we used the Binary instance for Text to serialise the event
name. This is wrong.
We now first encode to UTF-8 and use this in the eventlog encoding.
> Fix string encodings.

- GhcEvents.hs
- ghc-events.cabal
- src/GHC/RTS/Events/Incremental.hs
Previous `ghc-events show` would fail to report malformed events. Here we fix this by splitting up `readEvents` to offer:
```haskell
readEvents' :: Header -> BL.ByteString -> [Either String Event]
```
Which gives the user access to event deserialisation errors.
Fixes #85.
> Ensure that `ghc-events show` fails with an error on malformed events

- CHANGELOG.md
- GhcEvents.hs
- ghc-events.cabal
Output in the usage help:
```console
david@Davids-MacBook-Air ghc-events % ghc-events
ghc-events --help:                        Display this help.
ghc-events --version                      Print the version of ghc-events.
ghc-events inc <file>:                    Pretty print an event log incrementally
ghc-events inc force <file>:              Pretty print an event log incrementally. Retry on incomplete input (aka 'tail -f').
ghc-events show <file>:                   Pretty print an event log.
ghc-events show threads <file>:           Pretty print an event log, ordered by threads.
ghc-events show caps <file>:              Pretty print an event log, ordered by capabilities.
ghc-events merge <out> <in1> <in2>:       Merge two event logs.
ghc-events sparks-csv <file>:             Print spark …
```
> Add --version option to ghc-events CLI

- GhcEvents.hs
- src/GHC/RTS/Events.hs
- src/GHC/RTS/Events/Incremental.hs
Compatibility with GHC < 8.* was dropped in https://github.com/haskell/ghc-events/pull/89 , so this PR removes some CPP which was used to guarantee compatibility with base versions which correspond to earlier GHC versions. See the table in: https://www.snoyman.com/base/
> Remove CPP which was used for compatibility with GHC < 8.*

- src/GHC/RTS/EventTypes.hs
- src/GHC/RTS/Events.hs
Support for Era profiling was added in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11903
> Add support for era event types

- .github/workflows/haskell-ci.yml
- ghc-events.cabal
I used `haskell-ci` from the current master branch of the haskell-ci repo, since the published version of haskell-ci doesn't support 9.10 yet.
> Add GHC 9.10.1 to the versions tested in CI

- CHANGELOG.md
- ghc-events.cabal
- src/GHC/RTS/EventTypes.hs
- src/GHC/RTS/Events.hs
- src/GHC/RTS/Events/Binary.hs
This is a CapNo rather than a CapSet.
The event stores this as an Int32, but CapNo is an Int16. So we need to do some conversions.
Resolves #84
NB: this is a breaking change, as we change the type and name of this field
> Fix type of ProfSampleCostCentre.profCapSet event field

- CHANGELOG.md
- ghc-events.cabal
- src/GHC/RTS/EventParserUtils.hs
- src/GHC/RTS/Events/Binary.hs
We already depend on vector, so let's just use that for all of our array needs
> Drop dependency on array

- CHANGELOG.md
- src/GHC/RTS/Events/Merge.hs
Unfortunately we can't drop this CPP yet, so this is a bit messy and requires putting the definition into another function.
> Make definition of Monoid MaxVars cannonical

- ghc-events.cabal
I have tested that this builds locally when i force it to use the right version of containers
Resolves https://github.com/haskell/ghc-events/issues/116
> Support containers-0.8

- src/GHC/RTS/Events/Analysis.hs
Exporting the `step` function allows users to run this machine incrementally. This is not possible with the currently  exported API, except by simply locally re-implementing the `step` function.
> Export step from GHC.RTS.Events.Analysis
